module.exports = [
    {
        pid: 70001,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - A",
    },
    {
        pid: 70002,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - B",
    },
    {
        pid: 70003,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - C",
    },
    {
        pid: 70004,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - D",
    },
    {
        pid: 70005,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - E",
    },
    {
        pid: 70006,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - F",
    },
    {
        pid: 70007,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - G",
    },
    {
        pid: 70008,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - H",
    },
    {
        pid: 70009,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - I",
    },
    {
        pid: 70010,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - J",
    },
    {
        pid: 70011,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - AA",
    },
    {
        pid: 70012,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - BB",
    },
    {
        pid: 70013,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - CC",
    },
    {
        pid: 70014,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - DD",
    },
    {
        pid: 70015,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - EE",
    },
    {
        pid: 70016,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - FF",
    },
    {
        pid: 70017,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - GG",
    },
    {
        pid: 70018,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - HH",
    },
    {
        pid: 70019,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - II",
    },
    {
        pid: 70020,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - JJ",
    },
    {
        pid: 70021,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - A",
    },
    {
        pid: 70022,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - B",
    },
    {
        pid: 70023,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - C",
    },
    {
        pid: 70024,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - D",
    },
    {
        pid: 70025,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - E",
    },
    {
        pid: 70026,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - F",
    },
    {
        pid: 70027,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - G",
    },
    {
        pid: 70028,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - H",
    },
    {
        pid: 70029,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - I",
    },
    {
        pid: 70030,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - J",
    },
    {
        pid: 70031,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - AA",
    },
    {
        pid: 70032,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - BB",
    },
    {
        pid: 70033,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - CC",
    },
    {
        pid: 70034,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - DD",
    },
    {
        pid: 70035,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - EE",
    },
    {
        pid: 70036,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - FF",
    },
    {
        pid: 70037,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - GG",
    },
    {
        pid: 70038,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - HH",
    },
    {
        pid: 70039,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - II",
    },
    {
        pid: 70040,
        inStock: 100,
        location: "Paint Shop",
        name: "Paint Component - JJ",
    },
]