module.exports = [
    {
        pid: 70001,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - A",
    },
    {
        pid: 70002,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - B",
    },
    {
        pid: 70003,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - C",
    },
    {
        pid: 70004,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - D",
    },
    {
        pid: 70005,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - E",
    },
    {
        pid: 70006,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - F",
    },
    {
        pid: 70007,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - G",
    },
    {
        pid: 70008,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - H",
    },
    {
        pid: 70009,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - I",
    },
    {
        pid: 70010,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - J",
    },
    {
        pid: 700011,
        inStock: 100,
        location: "Paint Shop",
        name: "Sand Blast Component - AA",
    },
    {
        pid: 70012,
        inStock: 100,
        location: "Paint Shop",
        name: "Painted Component - A",
    },
    {
        pid: 70013,
        inStock: 100,
        location: "Paint Shop",
        name: "Painted Component - AA",
    },
]