module.exports = [
    {
        dept_number: 100,
        email: "abullock@g2systems.com",
        first_name: "Aimee",
        id_num: 1,
        last_name: "Bullock",
        password: "aimeeb123",
        pay: 75000,
        salary: true,
        start_date: '2005-01-12',
        wc_id: 101
    },
    {
        dept_number: 100,
        email: "ghenry@g2systems.com",
        first_name: "Garrett",
        id_num: 2,
        last_name: "Henry",
        password: "garretth123",
        pay: 75000,
        salary: true,
        start_date: '2004-05-20',
        wc_id: 101
    },
    {
        dept_number: 100,
        email: "toneal@g2systems.com",
        first_name: "Troy",
        id_num: 3,
        last_name: "Oneal",
        password: "troyo123",
        pay: 75000,
        salary: true,
        start_date: '2003-03-04',
        wc_id: 101
    },
    {
        dept_number: 100,
        email: "ndickerson@g2systems.com",
        first_name: "Natalie",
        id_num: 4,
        last_name: "Dickerson",
        password: "natalied123",
        pay: 75000,
        salary: true,
        start_date: '2006-12-10',
        wc_id: 102
    },
    {
        dept_number: 100,
        email: "hmorrow@g2systems.com",
        first_name: "Harold",
        id_num: 5,
        last_name: "Morrow",
        password: "haroldm123",
        pay: 75000,
        salary: true,
        start_date: '2002-09-15',
        wc_id: 102
    },
    {
        dept_number: 100,
        email: "lmuller@g2systems.com",
        first_name: "Lucille",
        id_num: 6,
        last_name: "Muller",
        password: "lucillem123",
        pay: 75000,
        salary: true,
        start_date: '2005-05-25',
        wc_id: 102
    },
    {
        dept_number: 100,
        email: "bweston@g2systems.com",
        first_name: "Benjamin",
        id_num: 7,
        last_name: "Weston",
        password: "benjaminw123",
        pay: 75000,
        salary: true,
        start_date: '2004-03-01',
        wc_id: 103
    },
    {
        dept_number: 100,
        email: "eclifford@g2systems.com",
        first_name: "Enrique",
        id_num: 8,
        last_name: "Clifford",
        password: "enriquec123",
        pay: 75000,
        salary: true,
        start_date: '2005-09-05',
        wc_id: 103
    },
    {
        dept_number: 200,
        email: "dwang@g2systems.com",
        first_name: "Debora",
        id_num: 9,
        last_name: "Wang",
        password: "deboraw123",
        pay: 85000,
        salary: true,
        start_date: '2003-02-07',
        wc_id: 201
    },
    {
        dept_number: 200,
        email: "lgibbs@g2systems.com",
        first_name: "Lillie",
        id_num: 10,
        last_name: "Gibbs",
        password: "lillieg123",
        pay: 85000,
        salary: true,
        start_date: '2003-06-12',
        wc_id: 201
    },
    {
        dept_number: 200,
        email: "smahoney@g2systems.com",
        first_name: "Stacey",
        id_num: 11,
        last_name: "Mahoney",
        password: "staceym123",
        pay: 85000,
        salary: true,
        start_date: '2004-07-21',
        wc_id: 201
    },
    {
        dept_number: 200,
        email: "dmclean@g2systems.com",
        first_name: "Devin",
        id_num: 12,
        last_name: "McLean",
        password: "devinm123",
        pay: 65000,
        salary: true,
        start_date: '2004-04-11',
        wc_id: 202
    },
    {
        dept_number: 200,
        email: "denglish@g2systems.com",
        first_name: "Doreen",
        id_num: 13,
        last_name: "English",
        password: "doreene123",
        pay: 65000,
        salary: true,
        start_date: '2007-01-05',
        wc_id: 202
    },
    {
        dept_number: 200,
        email: "ebryant@g2systems.com",
        first_name: "Emma",
        id_num: 14,
        last_name: "Bryant",
        password: "emmab123",
        pay: 65000,
        salary: true,
        start_date: '2006-04-09',
        wc_id: 203
    },
    {
        dept_number: 200,
        email: "hroach@g2systems.com",
        first_name: "Hector",
        id_num: 15,
        last_name: "Roach",
        password: "hectorr123",
        pay: 65000,
        salary: true,
        start_date: '2009-04-09',
        wc_id: 203
    },
    {
        dept_number: 300,
        email: "pconway@g2systems.com",
        first_name: "Pauline",
        id_num: 16,
        last_name: "Conway",
        password: "paulinec123",
        pay: 65000,
        salary: true,
        start_date: '2006-02-19',
        wc_id: 301
    },
    {
        dept_number: 300,
        email: "charmon@g2systems.com",
        first_name: "Clinton",
        id_num: 17,
        last_name: "Harmon",
        password: "clintonh123",
        pay: 65000,
        salary: true,
        start_date: '2005-10-01',
        wc_id: 301
    },
    {
        dept_number: 300,
        email: "kblack@g2systems.com",
        first_name: "Kristina",
        id_num: 18,
        last_name: "Black",
        password: "kristinab123",
        pay: 15,
        salary: false,
        start_date: '2005-08-01',
        wc_id: 302
    },
    {
        dept_number: 300,
        email: "jroot@g2systems.com",
        first_name: "Johnnie",
        id_num: 19,
        last_name: "Root",
        password: "johnnier123",
        pay: 17.50,
        salary: false,
        start_date: '2005-07-01',
        wc_id: 302
    },
    {
        dept_number: 300,
        email: "kbarrera@g2systems.com",
        first_name: "Kathleen",
        id_num: 20,
        last_name: "Barrera",
        password: "kathleenb123",
        start_date: '2005-06-01',
        wc_id: 303
    },
    {
        dept_number: 300,
        email: "jroth@g2systems.com",
        first_name: "Jim",
        id_num: 21,
        last_name: "Roth",
        password: "jimr123",
        pay: 15,
        salary: false,
        start_date: '2005-05-01',
        wc_id: 303
    },
    {
        dept_number: 300,
        email: "msolis@g2systems.com",
        first_name: "Marjorie",
        id_num: 22,
        last_name: "Solis",
        password: "marjories123",
        pay: 16.50,
        salary: false,
        start_date: '2005-04-01',
        wc_id: 303
    },
    {
        dept_number: 300,
        email: "lsanchez@g2systems.com",
        first_name: "Lucy",
        id_num: 23,
        last_name: "Sanchez",
        password: "lucys123",
        pay: 17.50,
        salary: false,
        start_date: '2005-03-01',
        wc_id: 304
    },
    {
        dept_number: 300,
        email: "frocha@g2systems.com",
        first_name: "Frederick",
        id_num: 24,
        last_name: "Rocha",
        password: "frederickr123",
        pay: 18,
        salary: false,
        start_date: '2005-02-01',
        wc_id: 304
    },
    {
        dept_number: 300,
        email: "prichard@g2systems.com",
        first_name: "Pete",
        id_num: 25,
        last_name: "Richard",
        password: "peter123",
        pay: 18.50,
        salary: false,
        start_date: '2005-01-01',
        wc_id: 304
    },
    {
        dept_number: 300,
        email: "lmadden@g2systems.com",
        first_name: "Larry",
        id_num: 53,
        last_name: "Madden",
        password: "larrym123",
        pay: 18,
        salary: false,
        start_date: '2017-01-01',
        wc_id: 304
    },
    {
        dept_number: 300,
        email: "sboone@g2systems.com",
        first_name: "Sue",
        id_num: 26,
        last_name: "Boone",
        password: "sueb123",
        pay: 17.50,
        salary: false,
        start_date: '2009-01-01',
        wc_id: 305
    },
    {
        dept_number: 300,
        email: "vlester@g2systems.com",
        first_name: "Vincent",
        id_num: 52,
        last_name: "Lester",
        password: "vincentl123",
        pay: 17.50,
        salary: false,
        start_date: '2016-01-01',
        wc_id: 305
    },
    {
        dept_number: 300,
        email: "dhyde@g2systems.com",
        first_name: "Dominic",
        id_num: 27,
        last_name: "Hyde",
        password: "dominich123",
        pay: 20,
        salary: false,
        start_date: '2009-02-01',
        wc_id: 306
    },
    {
        dept_number: 300,
        email: "pjimenez@g2systems.com",
        first_name: "Peggy",
        id_num: 28,
        last_name: "Jimenez",
        password: "peggyj123",
        pay: 65000,
        salary: true,
        start_date: '2009-03-01',
        wc_id: 307
    },
    {
        dept_number: 300,
        email: "rbradford@g2systems.com",
        first_name: "Rob",
        id_num: 51,
        last_name: "Bradford",
        password: "robb123",
        pay: 20,
        salary: false,
        start_date: '2015-03-01',
        wc_id: 307
    },
    {
        dept_number: 300,
        email: "rcook@g2systems.com",
        first_name: "Roman",
        id_num: 29,
        last_name: "Cook",
        password: "romanc123",
        pay: 18.50,
        salary: false,
        start_date: '2009-04-01',
        wc_id: 308
    },
    {
        dept_number: 300,
        email: "tkatz@g2systems.com",
        first_name: "Tanya",
        id_num: 48,
        last_name: "Katz",
        password: "tanyak123",
        pay: 20,
        salary: false,
        start_date: '2015-04-01',
        wc_id: 308
    },
    {
        dept_number: 300,
        email: "bgroves@g2systems.com",
        first_name: "Ben",
        id_num: 49,
        last_name: "Groves",
        password: "beng123",
        pay: 21.50,
        salary: false,
        start_date: '2016-04-01',
        wc_id: 308
    },
    {
        dept_number: 300,
        email: "ftravis@g2systems.com",
        first_name: "Floyd",
        id_num: 50,
        last_name: "Travis",
        password: "floydt123",
        pay: 21.50,
        salary: false,
        start_date: '2016-09-01',
        wc_id: 308
    },
    {
        dept_number: 300,
        email: "sgreer@g2systems.com",
        first_name: "Seth",
        id_num: 30,
        last_name: "Greer",
        password: "sethg123",
        pay: 16.50,
        salary: false,
        start_date: '2009-05-01',
        wc_id: 309
    },
    {
        dept_number: 300,
        email: "bward@g2systems.com",
        first_name: "Bennie",
        id_num: 44,
        last_name: "Ward",
        password: "benniew123",
        pay: 16.50,
        salary: false,
        start_date: '2008-05-01',
        wc_id: 309
    },
    {
        dept_number: 300,
        email: "mmccarthy@g2systems.com",
        first_name: "Madeline",
        id_num: 45,
        last_name: "McCarthy",
        password: "madelinem123",
        pay: 18.25,
        salary: false,
        start_date: '2008-08-01',
        wc_id: 309
    },
    {
        dept_number: 300,
        email: "ccochran@g2systems.com",
        first_name: "Colin",
        id_num: 46,
        last_name: "Cochran",
        password: "colinc123",
        pay: 18,
        salary: false,
        start_date: '2012-08-01',
        wc_id: 309
    },
    {
        dept_number: 300,
        email: "wolsen@g2systems.com",
        first_name: "Willie",
        id_num: 47,
        last_name: "Olsen",
        password: "willieo123",
        pay: 17.25,
        salary: false,
        start_date: '2015-08-01',
        wc_id: 309
    },
    {
        dept_number: 300,
        email: "doliver@g2systems.com",
        first_name: "Dwight",
        id_num: 31,
        last_name: "Oliver",
        password: "dwighto123",
        pay: 50000,
        salary: true,
        start_date: '2009-06-01',
        wc_id: 310
    },
    {
        dept_number: 300,
        email: "rowens@g2systems.com",
        first_name: "Ray",
        id_num: 41,
        last_name: "Owens",
        password: "rayo123",
        pay: 17.50,
        salary: false,
        start_date: '2010-06-01',
        wc_id: 310
    },
    {
        dept_number: 300,
        email: "bkuhn@g2systems.com",
        first_name: "Bud",
        id_num: 42,
        last_name: "Kuhn",
        password: "budk123",
        pay: 17.25,
        salary: false,
        start_date: '2010-09-01',
        wc_id: 310
    },
    {
        dept_number: 300,
        email: "dgrey@g2systems.com",
        first_name: "Dawn",
        id_num: 43,
        last_name: "Grey",
        password: "dawng123",
        pay: 18.50,
        salary: false,
        start_date: '2010-10-01',
        wc_id: 310
    },
    {
        dept_number: 400,
        email: "wswanson@g2systems.com",
        first_name: "Wayne",
        id_num: 32,
        last_name: "Swanson",
        password: "waynes123",
        pay: 85000,
        salary: true,
        start_date: '2009-07-01',
        wc_id: 401
    },
    {
        dept_number: 400,
        email: "msnyder@g2systems.com",
        first_name: "Marcia",
        id_num: 33,
        last_name: "Snyder",
        password: "marcias123",
        pay: 87500,
        salary: true,
        start_date: '2009-08-01',
        wc_id: 401
    },
    {
        dept_number: 400,
        email: "dbryant@g2systems.com",
        first_name: "Donald",
        id_num: 34,
        last_name: "Bryant",
        password: "donaldb123",
        pay: 80000,
        salary: true,
        start_date: '2009-09-01',
        wc_id: 402
    },
    {
        dept_number: 400,
        email: "lstephenson@g2systems.com",
        first_name: "Lee",
        id_num: 35,
        last_name: "Stephenson",
        password: "lees123",
        pay: 70000,
        salary: true,
        start_date: '2009-10-01',
        wc_id: 402
    },
    {
        dept_number: 500,
        email: "arice@g2systems.com",
        first_name: "Al",
        id_num: 36,
        last_name: "Rice",
        password: "alr123",
        pay: 70000,
        salary: true,
        start_date: '2009-10-01',
        wc_id: 501
    },
    {
        dept_number: 500,
        email: "mstanton@g2systems.com",
        first_name: "Morgan",
        id_num: 37,
        last_name: "Stanton",
        password: "morgans123",
        pay: 65000,
        salary: true,
        start_date: '2009-11-01',
        wc_id: 501
    },
    {
        dept_number: 600,
        email: "wlarson@g2systems.com",
        first_name: "Wesley",
        id_num: 38,
        last_name: "Larson",
        password: "wesleyl123",
        pay: 60000,
        salary: true,
        start_date: '2009-12-01',
        wc_id: 601
    },
    {
        dept_number: 600,
        email: "gbentley@g2systems.com",
        first_name: "Glen",
        id_num: 39,
        last_name: "Bentley",
        password: "glenb123",
        pay: 82500,
        salary: true,
        start_date: '2010-01-01',
        wc_id: 601
    },
    {
        dept_number: 600,
        email: "jpham@g2systems.com",
        first_name: "Janette",
        id_num: 40,
        last_name: "Pham",
        password: "janettep123",
        pay: 60000,
        salary: true,
        start_date: '2010-02-01',
        wc_id: 602
    }
]